---
# General
label: Agent

# Ledger
no-ledger: true

# Wallet
auto-provision: true
wallet-type: askar
wallet-name: agent_wallet
wallet-storage-type: postgres_storage
wallet-allow-insecure-seed: true
wallet-local-did: true

# Admin
admin: [ 0.0.0.0, 8020 ]
admin-insecure-mode: true

# Multitenant
# multitenant: true
# multitenant-admin: true

# Transport
inbound-transport: 
  - [ http, 0.0.0.0, 8021 ]
  - [ ws, 0.0.0.0, 8022 ]
outbound-transport:
  - http
  - ws

# Connections
auto-accept-intro-invitation-requests: true
auto-accept-invites: true
auto-accept-requests: true
auto-respond-messages: true
auto-ping-connection: true

# Credentials
auto-respond-credential-proposal: true
auto-respond-credential-offer: true
auto-respond-credential-request: true
auto-store-credential: true

# Discovery
auto-disclose-features: true

# Presentations
auto-respond-presentation-proposal: true
auto-respond-presentation-request: true
auto-verify-presentation: true

# Exchanges
preserve-exchange-records: true

# Revocation
notify-revocation: true